### ISSUE TITLE
http2 unconditionally enabled with shared libcurl, ignoring `http2` feature

### ISSUE THREAD

**Issue by Shnatsel** [sagebind/isahc#147] opened 2020-01-04 15:20 UTC
When compiling isahc without the `http2` feature and using the system-wide libcurl, HTTP/2 protocol support is enabled anyway, disregarding the feature configuration.

This is a problem because some websites (1000 out of [the top million](https://blog.majestic.com/development/majestic-million-csv-daily/)) redirect to HTTP/2 and then fail (at least under libcurl), but work fine if the client doesn't support HTTP/2.

Tested on commit 3a815fe3cb6c2e142cc23731eafde998b9a3cb54. Please be aware of https://github.com/alexcrichton/curl-rust/issues/316 which may complicate testing.

**Comment by sagebind** [comment] 2020-01-04 18:41
Could you elaborate on this a bit more? I'm not entirely sure what the problem is. Particularly with

> redirect to HTTP/2 and then fail (at least under libcurl), but work fine if the client doesn't support HTTP/2.

By redirect do you mean an HTTP/2 upgrade? Perhaps an example of a failed request would help me understand here.

> When compiling isahc without the `http2` feature and using the system-wide libcurl, HTTP/2 protocol support is enabled anyway, disregarding the feature configuration.

That is correct, there are a number of features that have no effect when using the system-wide libcurl, because we don't have much control over it. Some of them, like `http2`, we _could_ tweak runtime behavior based on it that would give _similar_ results, but I would be concerned about increasing complexity of the possible behaviors.

Current behavior when using system-wide libcurl is that newer libcurl versions will default to preferring HTTP/2 if supported, older versions default to HTTP/1.1 (even if HTTP/2 support is enabled), and if HTTP/2 support is not available it is never asked for. It all depends at runtime on which version of libcurl is used and how it was compiled.

**Comment by Shnatsel** [comment] 2020-01-04 18:58
> By redirect do you mean an HTTP/2 upgrade? Perhaps an example of a failed request would help me understand here.

Here's one example of a website that errors out on HTTP2:
```
$ curl --http2 iomega.com -I
HTTP/1.1 101 Switching Protocols
connection: Upgrade
upgrade: h2c

curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
$ curl iomega.com -I
HTTP/1.1 429 Too Many Requests
cache-control: max-age=0, private, must-revalidate
connection: close
content-length: 17
date: Sat, 04 Jan 2020 18:56:14 GMT
server: nginx
set-cookie: sid=e1d6f644-2f23-11ea-ae09-447ada9a2f3c; path=/; domain=.iomega.com; expires=Thu, 22 Jan 2088 22:10:21 GMT; max-age=2147483647; HttpOnly
```
There is just over 1000 of those among the top million websites. I can compile a full list if you're interested.

**Comment by Shnatsel** [comment] 2020-01-04 19:00
> That is correct, there are a number of features that have no effect when using the system-wide libcurl, because we don't have much control over it.

In that case the name of the feature is misleading. It should be `static-curl-http2` or similar.

**Comment by sagebind** [comment] 2020-01-04 19:16
Ah, I think I understand what you are asking now. Basically the problem is that there are some websites which claim to support HTTP/2, and so we attempt to upgrade to it. But it implements HTTP/2 _incorrectly_ and produces the error. So ultimately, regardless of whether HTTP/2 is _supported_ (which is what the compile-time features might do) you would like to not attempt to use HTTP/2 at all.

If my assessment is correct, then the Isahc feature you are looking for is called [`VersionNegotiation`](https://docs.rs/isahc/0.8.2/isahc/config/struct.VersionNegotiation.html). Here's a tiny but complete example that would work for such a site (like the one you provided):

```rust
use isahc::{
    config::VersionNegotiation,
    prelude::*,
};

fn main() -> Result<(), isahc::Error> {
    let mut response = Request::get("http://iomega.com")
        .version_negotiation(VersionNegotiation::http11())
        .body(())?
        .send()?;

    println!("Status: {}", response.status());
    println!("Headers: {:?}", response.headers());
    println!("{}", response.text()?);

    Ok(())
}
```

**Comment by Shnatsel** [comment] 2020-01-04 19:21
Thanks for the code snippet, this looks like it should do the trick!

Could you consider creating an alias `static-curl-http2` for the `http2` feature and referring to the alias in the docs, to avoid such confusion in the future?

**Comment by sagebind** [comment] 2020-01-04 19:34
I'll definitely work on significantly improving the documentation for that crate feature. I'm not convinced that this is enough to warrant moving towards changing the feature's name though.

**Comment by Shnatsel** [comment] 2020-01-04 19:38
Frankly when selecting features I look at feature names and assume them to be self-explanatory instead of reading the docs. Although a comment in `Cargo.toml` would definitely help.

Changing the feature's name would be a breaking change, so I suggest simply making a more readable alias for it.

**Comment by sagebind** [comment] 2020-01-04 19:45
I created #148 to make sure that the docs get improved, and thank you for taking the time to fill out this issue! Specifically I want to make it easy to understand the distinction between compile-time support and runtime selection. Feature flags (even if they behaved how you expected) are not the right place to select HTTP versions. What if you need to talk to more than one server, and they both require different choices of versions? Or multipe crates depend on Isahc and end up in the same binary, but need to use different versions?

> Changing the feature's name would be a breaking change, so I suggest simply making a more readable alias for it.

An alias seems like a weird thing to do unless you _intend_ to rename the feature in the next breaking release (though you wouldn't cut a breaking version for that change alone).

**Comment by sagebind** [comment] 2020-01-04 20:14
It also may be worth considering that the `http2` feature upstream is a little more nuanced than simply toggling HTTP/2 support when static curl is enabled. For example, when `http2` enabled, even if `static-curl` is not requested _and_ a system libcurl is available, if the system libcurl does _not_ have http2 enabled, then we actually use a bundled libcurl anyway (so that HTTP/2 can be enabled since we control its compilation).

**Comment by sagebind** [comment] 2020-01-09 01:30
Closing this question out. Feel free to reach out anytime if you have any more questions or comments!

**Closed by sagebind** 2020-01-09 01:30 UTC
Labels: question
