### ISSUE TITLE
Why does the performance of isahc fluctuate so much?

### ISSUE THREAD

**Issue by milescui** [sagebind/isahc#275] opened 2020-12-11 13:54 UTC
Why does the performance of isahc fluctuate so much? There is no such problem when using nodejs to make the same request.

rust version: 1.50.0 nightly
os: ubuntu server 20.04.1
intel 16 cores 3.6Ghz, and 32G mem.

Command:
cargo run --release

[profile.release]
lto = true
codegen-units = 1

[dependencies.isahc]
version = "1.0.0-BETA.1"
default-features = false
features = ["static-curl", "text-decoding", "json", "http2"]

rust code:

```rust
use std::time::Instant;

use rsex::binance::spot_rest::Binance;
use rsex::constant::{ORDER_SIDE_BUY, ORDER_TYPE_POST_ONLY};
use rsex::traits::SpotRest;
use uuid::Uuid;

const API_KEY: &'static str = "";
const SECRET_KEY: &'static str = "";
const HOST: &'static str = "https://api.binance.com";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();

    let mut api = Binance::new(Some(API_KEY.into()), Some(SECRET_KEY.into()), HOST.into());
    api.set_spot();

    let mut api2 = Binance::new(Some(API_KEY.into()), Some(SECRET_KEY.into()), HOST.into());
    api2.set_spot();

    for _ in 0..50 {
        let before = Instant::now();
        // create_order
        let order = api
            .create_order(
                "WAVESUSDT",
                6.2,
                2.03,
                ORDER_SIDE_BUY,
                ORDER_TYPE_POST_ONLY,
                Option::from(Uuid::new_v4().to_string().replace("-", "").as_str()),
            )
            .unwrap();
        println!("create_order Elapsed time: {:.3?}", before.elapsed());

        let canceled_order_before = Instant::now();
        let _canceled_order = api2.cancel(&*order.id, Option::from("WAVESUSDT"));
    }

    Ok(())
}
```

```rust
pub fn create_order(
        &self,
        symbol: &str,
        price: f64,
        amount: f64,
        side: &str,
        ty: &str,
        cid: Option<&str>,
    ) -> APIResult<Order> {
        let uri = if self.is_margin {
            MARGIN_URI.get("create_order").unwrap()
        } else {
            SPOT_URI.get("create_order").unwrap()
        };
        let mut params: BTreeMap<String, String> = BTreeMap::new();
        params.insert("symbol".into(), symbol.into());
        params.insert("side".into(), side.into());
        if ty == ORDER_TYPE_POST_ONLY {
            params.insert("type".into(), "LIMIT_MAKER".into());
        } else {
            params.insert("type".into(), ty.into());
        }
        if ty == ORDER_TYPE_LIMIT {
            params.insert("timeInForce".into(), "GTC".into());
        }
        if let Some(cid) = cid {
            params.insert("newClientOrderId".into(), cid.into());
        }
        if ty == ORDER_TYPE_LIMIT || ty == ORDER_TYPE_POST_ONLY {
            params.insert("price".into(), price.to_string());
        }

        params.insert("quantity".into(), amount.to_string());
        let req = self.build_signed_request(params)?;

        let ret = self.post_signed(uri, &req)?;
        let resp: bn_types::OrderResult = serde_json::from_str(&ret)?;

        let order = Order {
            symbol: symbol.to_string(),
            id: resp.order_id.to_string(),
            cid: resp.client_order_id.to_string(),
            price,
            amount,
            filled: 0.0,
            side: side.to_string(),
            ty: ty.to_string(),
            status: ORDER_STATUS_SUBMITTED,
            timestamp: get_timestamp().unwrap_or(0),
        };

        Ok(order)
    }
```

```rust
pub fn post_signed(&self, endpoint: &str, request: &str) -> APIResult<String> {
        let url = self.sign(endpoint, request);

        let resp = Request::post(url)
            .header(
                CONTENT_TYPE,
                HeaderValue::from_static("application/x-www-form-urlencoded"),
            )
            .header(
                HeaderName::from_static("x-mbx-apikey"),
                HeaderValue::from_str(self.api_key.as_str())?,
            )
            .body(())
            .unwrap()
            .send()?;
        self.handler(resp)
}
```

**Result:**

```shell
create_order Elapsed time: 33.820ms
create_order Elapsed time: *21.518ms*
create_order Elapsed time: 14.957ms
create_order Elapsed time: 12.281ms
create_order Elapsed time: 14.139ms
create_order Elapsed time: *24.132ms*
create_order Elapsed time: 12.492ms
create_order Elapsed time: 15.795ms
create_order Elapsed time: 15.112ms
create_order Elapsed time: 11.093ms
create_order Elapsed time: 14.955ms
create_order Elapsed time: 14.582ms
create_order Elapsed time: 12.036ms
create_order Elapsed time: 14.369ms
create_order Elapsed time: 14.668ms
create_order Elapsed time: *47.143ms*
create_order Elapsed time: 10.871ms
create_order Elapsed time: 10.203ms
create_order Elapsed time: 16.487ms
create_order Elapsed time: 15.530ms
create_order Elapsed time: 13.396ms
create_order Elapsed time: 8.893ms
create_order Elapsed time: 16.934ms
create_order Elapsed time: 14.505ms
create_order Elapsed time: *19.209ms*
create_order Elapsed time: 12.595ms
create_order Elapsed time: 15.070ms
create_order Elapsed time: 14.381ms
create_order Elapsed time: *71.105ms*
create_order Elapsed time: 12.785ms
create_order Elapsed time: 10.448ms
create_order Elapsed time: *23.419ms*
create_order Elapsed time: 14.546ms
create_order Elapsed time: 12.037ms
create_order Elapsed time: 11.329ms
create_order Elapsed time: 10.761ms
create_order Elapsed time: *19.813ms*
create_order Elapsed time: 10.913ms
create_order Elapsed time: 9.647ms
create_order Elapsed time: 15.233ms
create_order Elapsed time: *17.813ms*
create_order Elapsed time: 9.451ms
create_order Elapsed time: 10.968ms
create_order Elapsed time: 15.417ms
create_order Elapsed time: 13.435ms
create_order Elapsed time: 10.235ms
create_order Elapsed time: 11.432ms
create_order Elapsed time: *61.210ms*
create_order Elapsed time: 15.418ms
create_order Elapsed time: *26.095ms*
```

**Comment by sagebind** [comment] 2020-12-11 15:20
Thanks for filing an issue! I'll do my best to address it.

What does the body of `handler` look like? Something that could be more clear from the docs is that it is preferable to consume the response body before dropping a response for performance. The reason is to ensure efficient connection re-use, but if you do not consume the response body, the connection cannot be reused. This is a common performance issue unfortunately.

**Comment by milescui** [comment] 2020-12-12 04:37
My handler:

```rust
fn handler(&self, mut resp: Response<Body>) -> APIResult<String> {
        match resp.status() {
            StatusCode::OK => {
                let body = resp.text()?;
                Ok(body)
            }
            StatusCode::TOO_MANY_REQUESTS => Err(Box::new(ExError::RateLimitExceeded(
                "rate limit exceeded: 429".into(),
            ))),
            StatusCode::IM_A_TEAPOT => Err(Box::new(ExError::IpBanned("ip banned: 418".into()))),
            s => {
                return Err(Box::new(ExError::ApiError(format!(
                    "response: {:?} {}",
                    s,
                    resp.text()?
                ))));
            }
        }
    }
```

**Comment by sagebind** [comment] 2020-12-12 20:25
OK, thanks for the quick response! I don't see anything wrong with that code either, that looks good.

Performance measuring is always tricky and time-consuming, so it may be a while before I can offer any concrete answers. That isn't to say that I care about performance, because I care a lot. All I can say is that I will continue working on performance, _especially_ post-1.0, since the 1.0 release was primarily oriented toward features and API stability. After 1.0 is released, performance tuning will probably be the focus. I _can_ reproduce behavior on Linux with response time fluctuations like you are seeing, so I'll definitely be looking at this when I can.

Based on all the profiling I've done already, the I/O selector can sometimes be a source of inconsistent socket readiness delays. At the moment I am using the driver provided by libcurl, but I already have plans to replace this with something better. You can track the issue for that in #17. One reason is that the libcurl default does a lot of extra syscalls that are unnecessary or could be batched together.

**Comment by milescui** [comment] 2020-12-13 05:46
Thanks. Looking forward to performance improvements.

**Comment by sagebind** [comment] 2021-07-28 00:16
Just sharing some updates on performance: Since the last update Isahc 1.0 has been released, and as promised some performance tuning has been done now that the API is stable. In particular [1.2.0](https://github.com/sagebind/isahc/releases/tag/1.2.0) should have noticeable performance improvements over 0.9.x. Feel free to give it a try; I'd love to hear about any performance changes you see (good _or_ bad)!

**Comment by sagebind** [comment] 2022-03-12 05:11
Closing as the I/O driver improvements have been out for some time now with several other big performance improvements since this issue was opened. If you are having any performance issues feel free to open a [discussion thread](https://github.com/sagebind/isahc/discussions).

**Closed by sagebind** 2022-03-12 05:11 UTC
Labels: performance
