### ISSUE TITLE
'agent thread terminated prematurely' on multiple requests

### ISSUE THREAD

**Issue by kathampy** [sagebind/isahc#98] opened 2019-10-21 06:19 UTC
As I ramp up the number of requests per second, it crashes. Some URLs crash at 250 requests / second, and some consistently crash at just 2 requests / second. What other debugging information can I provide?

I found that HTTP/1.1 connections to a particular URL do not crash even at 7000 requests / second, and only HTTP/2 connections with probably 50+ streams crash.

The crash is related to the response time of the server. URLs that take 2-3 seconds crash at 2 requests / second.

```
isahc/0.7.4 (features:chrono,cookies,default,http2,static_curl) libcurl/7.66.0-DEV SecureTransport zlib/1.2.11 nghttp2/1.33.90

thread 'actix-rt:worker:0' panicked at 'agent thread terminated prematurely', /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/isahc-0.7.4/src/agent.rs:161:17
stack backtrace:
   0:        0x101df2542 - std::panicking::default_hook::{{closure}}::h3f994bbc901f9889
   1:        0x101df220d - std::panicking::default_hook::h6c261b7dad1af707
   2:        0x101df2c80 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::hdaf0f2c7e6fec8f5
   3:        0x101e1541e - bytes::bytes::abort::h74525b449fc5d119
   4:        0x101731701 - isahc::agent::Handle::send_message::h0a54373593c9aa13
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/isahc-0.7.4/src/agent.rs:161
   5:        0x101731674 - isahc::agent::Handle::submit_request::h89c140f8dfae13f8
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/isahc-0.7.4/src/agent.rs:147
   6:        0x10171a7e3 - isahc::client::ResponseFuture::maybe_initialize::hca9c4949de41e29f
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/isahc-0.7.4/src/client.rs:911
   7:        0x10171b090 - <isahc::client::ResponseFuture as core::future::future::Future>::poll::he647e4025b5ff9ea
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/isahc-0.7.4/src/client.rs:966
   8:        0x10164e874 - <F as futures_core::future::TryFuture>::try_poll::h63b3f8ff232a01df
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.19/src/future/mod.rs:86
   9:        0x1016e5637 - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::{{closure}}::h8410e40593cde2aa
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/compat/compat03as01.rs:122
  10:        0x1016e5039 - futures_util::compat::compat03as01::with_context::h6e3900429172ce0d
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/compat/compat03as01.rs:224
  11:        0x1016e55dc - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::hcae8189fca766ffa
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.19/src/compat/compat03as01.rs:122
  12:        0x1016eb5a9 - futures::future::chain::Chain<A,B,C>::poll::hd6cd38a9558bcbe9
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26
  13:        0x1016a654f - <futures::future::then::Then<A,B,F> as futures::future::Future>::poll::h40164ab9e33074ba
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32
  14:        0x1016d9c71 - <futures::future::either::Either<A,B> as futures::future::Future>::poll::he2aae3cb92556df9
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/either.rs:36
  15:        0x1016db79a - <actix_web::handler::AsyncHandlerServiceResponse<T> as futures::future::Future>::poll::hd4fb517fc1719809
                               at /Users/Kurian/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-1.0.8/src/handler.rs:249
```

**Comment by kathampy** [comment] 2019-10-21 07:14
It seems to be due to not consuming the `body`. I just want to read the headers and discard the body. I thought the body would be discarded cleanly once it goes out of scope. Is there something I should do to discard the body without reading it?

**Comment by sagebind** [comment] 2019-10-21 16:08
This is possibly a duplicate of #97.

**Comment by sagebind** [comment] 2019-10-21 16:09
> Is there something I should do to discard the body without reading it?

No, dropping the `Body` ought to be sufficient to abort the request.

**Comment by kathampy** [comment] 2019-10-21 16:12
I can confirm that consuming the body in a future with `tokio::io::read_to_end()` stops the crashes completely.
> No, dropping the `Body` ought to be sufficient to abort the request.
What if I only read the response status and don't get a reference to the body at all?

**Comment by sagebind** [comment] 2019-10-22 00:53
> What if I only read the response status and don't get a reference to the body at all?
It exists whether you get a reference or not; dropping the `Response<Body>` naturally drops the inner `Body`.

**Comment by sagebind** [comment] 2019-10-22 00:56
Closing this in favor of #97, which appears to be the same bug. Let's move the conversation into there to keep information centralized.

**Closed by sagebind** 2019-10-22 00:56 UTC
Labels: bug
